# Basics of numpy

In [2]:
import numpy as np

### creating array from list

In [8]:
arr_1d = np.array([1, 2, 3, 4 ,5])
print("arr_1d: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("arr_2d: ", arr_2d)

arr_1d:  [1 2 3 4 5]
arr_2d:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [16]:
# can stores different types of elements
py_list = [1, 2, 3, 4.3, 'Rohit', {"key": "value"}]
print("Python list multiplication: ", py_list*2)

# stores only one type of elements
np_array = np.array([1, 2, 3, 4]) 
print("numpy array multiplication: ", np_array*2)


Python list multiplication:  [1, 2, 3, 4.3, 'Rohit', {'key': 'value'}, 1, 2, 3, 4.3, 'Rohit', {'key': 'value'}]
numpy array multiplication:  [2 4 6 8]


### Creating array from scratch

In [10]:
zeroes_1d = np.zeros(5)
zeroes_2d = np.zeros((3, 4))
print("1d Zeroes: ", zeroes_1d)
print("2d Zeroes: \n", zeroes_2d)

zeros = np.zeros(5, int) # zeros(n, datatype)
print("zeros: ", zeros)

ones = np.ones(5, int) # zeros(n, datatype)
print("ones: ", ones)

full = np.full((2,3), 7)
print("full: \n", full)

random = np.random.random((2, 3))
print("Random: \n", random)

randint = np.random.randint(10, 20) # generate integer random no. from 10 to 19
print("Random integer: ", randint)

1d Zeroes:  [0. 0. 0. 0. 0.]
2d Zeroes: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros:  [0 0 0 0 0]
ones:  [1 1 1 1 1]
full: 
 [[7 7 7]
 [7 7 7]]
Random: 
 [[0.740828   0.49288645 0.5890974 ]
 [0.3388649  0.52826304 0.69719391]]
Random integer:  18


### arange()

In [24]:
sequence1 = np.arange(10) # arange(start, stop, stepsize)
sequence2 = np.arange(2, 12, 2)
sequence3 = np.arange(10, 1, -1)
sequence4 = np.arange(0, 11, 1.5)

print("Sequence1 : ", sequence1)
print("Sequence2 : ", sequence2)
print("Sequence3 : ", sequence3)
print("Sequence4 : ", sequence4)

Sequence1 :  [0 1 2 3 4 5 6 7 8 9]
Sequence2 :  [ 2  4  6  8 10]
Sequence3 :  [10  9  8  7  6  5  4  3  2]
Sequence4 :  [ 0.   1.5  3.   4.5  6.   7.5  9.  10.5]


### Attributes of an Array

In [44]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print("Dimension: ", arr.ndim)
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("dType: ", arr.dtype)
print("ItemSize: ", arr.itemsize)
print("nBytes: ", arr.nbytes)


Dimension:  2
Shape:  (2, 3)
Size:  6
dType:  int64
ItemSize:  8
nBytes:  48


### Vector operations

In [18]:
# `shape` has to be same
a1  = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[2, 2, 2], [1, -1, 2]])

print("Addition: \n", a1 + a2)
print("Subtraction: \n", a1 - a2)
print("Multiplication: \n", a1 * a2)
print("Division: \n", a1 / a2)

Addition: 
 [[3 4 5]
 [5 4 8]]
Subtraction: 
 [[-1  0  1]
 [ 3  6  4]]
Multiplication: 
 [[ 2  4  6]
 [ 4 -5 12]]
Division: 
 [[ 0.5  1.   1.5]
 [ 4.  -5.   3. ]]


### Array Reshaping

In [57]:
arr = np.arange(10)
print("Original Array: ", arr)

# the new array should have the same number of elements as in the original array
# returns a view, instead of copy
reshaped = arr.reshape((2, 5))
print("Reshaped Array: ", reshaped)

Original Array:  [0 1 2 3 4 5 6 7 8 9]
Reshaped Array:  [[0 1 2 3 4]
 [5 6 7 8 9]]


### Array Flattening

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Original Array: ", arr)

# returns a copy
flattend = arr.flatten()
print("Flatten Array: ", flattend)

# return view , instead of copy
raveled = arr.ravel()
print("Ravel Array: ", raveled)

Original Array:  [[1 2 3]
 [4 5 6]]
Flatten Array:  [1 2 3 4 5 6]


### Array Transpose

In [54]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Original Array: ", arr)

# return view , instead of copy
transpose = arr.T
print("Transposed Array: ", transpose)


Original Array:  [[1 2 3]
 [4 5 6]]
Transposed Array:  [[1 4]
 [2 5]
 [3 6]]


### View

In [64]:
print("Memory Block : 1 2 3 4\n")
# Both are just different `views` of the `same memory block`.

arr = np.array([1, 2, 3, 4])
print("Array: ", arr)

reshaped = arr.reshape(2, 2)
print("Reshaped: ", reshaped)

# change original array
arr[0] = 100

print("\nAfter changing arr:")
print("Reshaped: ", reshaped)

# change reshaped array
reshaped[1][1] = 999

print("\nAfter changing reshaped:")
print("Array: ", arr)

# Checking Shared Memory
print("\nDo they share memory?")
print(np.shares_memory(arr, reshaped))

Memory Block : 1 2 3 4

Array:  [1 2 3 4]
Reshaped:  [[1 2]
 [3 4]]

After changing arr:
Reshaped:  [[100   2]
 [  3   4]]

After changing reshaped:
Array:  [100   2   3 999]

Do they share memory?
True
