# Numpy Operations

In [2]:
import numpy as np

### Indexing and Slicing

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# retrieve from 1st to prior to 6th element in steps of 2
a = arr[1:6:2]
# retrieve all elements from arr
b = arr[::]
# retrieve from 8-2 = 6th to one element prior to 2nd element in decreasing step size
c = arr[-2:4:-1]
# retreive from 0th to one prior element to 4th element (6-2 = 4th) with deafult stepsize of 1
d = arr[:-2:]

print("arr : ", arr)
print("a : ", a)
print("b : ", b)
print("c : ", c)
print("d : ", d)

arr :  [1 2 3 4 5 6 7 8]
a :  [2 4 6]
b :  [1 2 3 4 5 6 7 8]
c :  [7 6]
d :  [1 2 3 4 5 6]


In [11]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Specific element: ", arr[1, 2])
print("Entire 1th row: ", arr[1])
print("Entire 1th column: ", arr[:, 1])
print("0th row to 1st row with columns from 0th col to 2nd col: \n", arr[:2, :3])

# display element by element
for i in range(len(arr)):
  for j in range(len(arr[i])):
    print(arr[i][j], end=" ")

Specific element:  6
Entire 1th row:  [4 5 6]
Entire 1th column:  [2 5 8]
0th row to 1st row with columns from 0th col to 2nd col: 
 [[1 2 3]
 [4 5 6]]
1 2 3 4 5 6 7 8 9 

### Sorting

In [15]:
# sort(matrix, axis)

arr_1d = np.array([2, 3, 2, 1, 17, 0, 7, 3, 5])
print("1D Sorted : \n", np.sort(arr_1d))

arr_2d = np.array([[5, 4, 1],
              [2, 7, 0]])

row_sorted = np.sort(arr_2d, axis=1) # default
print("Row wise Sorting: \n", row_sorted)
col_sorted = np.sort(arr_2d, axis=0)
print("Column wise Sorting: \n", col_sorted)

1D Sorted : 
 [ 0  1  2  2  3  3  5  7 17]
Row wise Sorting: 
 [[1 4 5]
 [0 2 7]]
Column wise Sorting: 
 [[2 4 0]
 [5 7 1]]


### Filter with Mask

In [ ]:
numbers = np.array([1, 4, 7, 2, 9, 5])

# produces a Boolean array
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

mask2 = numbers % 2 != 0
print("Odd numbers: ", numbers[mask2])

mask3 = (numbers < 5) & (numbers % 2 != 0)
print("Conditional numbers: ", numbers[mask3])

[False False  True False  True False]
Numbers greater than 5:  [7 9]
Odd numbers:  [1 7 9 5]
Conditional numbers:  [1]


### Fancy Indices and Where()

In [35]:
numbers = np.array([1, 4, 7, 2, 9, 5])
idices = [0, 2, 4]
print(numbers[idices])

# return indices where condition is true
where_reult = np.where(numbers > 5)
print("numbers where no. > 5: ", numbers[where_reult])

# where(condition, value_if_true, value_if_false)
condition_arr1 = np.where(numbers % 2 != 0, numbers*10, numbers)
print("Conditional array1: ", condition_arr1)

condition_arr2 = np.where(numbers % 2 == 0, 69, 100)
print("Conditional array2: ", condition_arr2)

[1 7 9]
numbers where no. > 5:  [7 9]
Conditional array1:  [10  4 70  2 90 50]
Conditional array2:  [100  69 100  69 100 100]


### vstack & hstack

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

row1 = np.array([[5, 6]])
row2 = np.array([[7, 8]])

row_arr = np.vstack((arr, row1, row2)) # top to bottom

print(row_arr)

col1 = np.array([[5], 
                 [6]])
col2 = np.array([[7], 
                 [8]])

col_arr = np.hstack((arr, col1, col2)) # left to right

print(col_arr)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 7]
 [3 4 6 8]]


### delete

In [13]:
# Creates new memory
# Copies all elements except deleted ones

arr = np.array([10, 20, 13, 8, 7, 22])

delete_one = np.delete(arr, 1)
delete_multiple = np.delete(arr, [1, 3, 5])

print(delete_one)
print(delete_multiple)

arr_2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

delete_row = np.delete(arr_2d, 1, axis=0) # Deleted row at index 1.
delete_col = np.delete(arr_2d, 1, axis=1) # Deleted column at index 1.

print(delete_row)
print(delete_col)

[10 13  8  7 22]
[10 13  7]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]
