## Matrices

In [2]:
import numpy as np

### Creating a Matrix

In [ ]:
# 1st way of creating
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
m = np.matrix(arr)
print(m)

# 2nd way of creating
str = '1 2; 3 4; 5 6' 
m1 = np.matrix(str)
print(m1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### Operations

In [ ]:
# find diagonal elements
mat = np.matrix(np.arange(1, 10).reshape(3, 3))
print(mat)
d = np.diagonal(mat)
print("Diagonal Elements: ", d)

# find max & min
maxi = mat.max()
mini = mat.min()
print("Max: ", maxi)
print("Min: ", mini)

# find sum & avg
add = mat.sum()
avg = mat.mean()
print("Sum: ", add)
print("Avg: ", avg)

# find product
row_product = mat.prod(1) # row-wise product
col_product = mat.prod(0) # column-wise product
print(row_product)
print(col_product)


# sorting
sort_arr = np.sort(mat)
print(sort_arr)

# transpose
trans = mat.T
print(trans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal Elements:  [1 5 9]
Max:  9
Min:  1
Sum:  45
Avg:  5.0
[[  6]
 [120]
 [504]]
[[ 28  80 162]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Addition , Subtraction, Division

In [17]:
a = np.matrix('1 2 3; 4 5 6')
b = np.matrix('2 2 2; 1 -1 2')

add = a + b
sub = a - b
div = a / b
print(add)
print(sub)
print(div)

[[3 4 5]
 [5 4 8]]
[[-1  0  1]
 [ 3  6  4]]
[[ 0.5  1.   1.5]
 [ 4.  -5.   3. ]]


### Multiplication

In [22]:
a = np.matrix('1 2 3; 4 5 6')
b = np.matrix('1 0; 0 2; 1 -1')

print(a)
print(b)
print(a.shape) # (2, 3)
print(b.shape) # (3, 2)

mul = a*b
print(mul)



[[1 2 3]
 [4 5 6]]
[[ 1  0]
 [ 0  2]
 [ 1 -1]]
(2, 3)
(3, 2)
[[ 4  1]
 [10  4]]
